# Generated by Django 3.0 on 2020-06-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Technologies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
